<?
unset($_SESSION['admin_username']);
unset($_SESSION['admin_id']);
unset($_SESSION['admin_name']);
unset($_SESSION['admin_product']);
unset($_SESSION['admin_admin']);
unset($_SESSION['admin_customer']);
unset($_SESSION['admin_order']);
unset($_SESSION['admin_news']);
unset($_SESSION['admin_system']);
returnPage_admin();
?>
